language: r
cache: packages
sudo: true
r: bioc-devel
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install ca-certificates
  - sudo add-apt-repository -y ppa:openjdk-r/ppa
  - sudo apt-get -qq update
  - sudo apt-get install -y openjdk-8-jdk
  - sudo update-java-alternatives -s java-1.8.0-openjdk-amd64
